development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:0a1ee827469da7250b0e571f92623953@soldierfish.redistogo.com:9374/
  channel_prefix: APILivePolling_production
